### ISSUE TITLE
Too many missing semicolons

### ISSUE THREAD

**Issue by DavidMatuszek** [fathominfo/processing-p5js-mode#25]
Statements that do not end in a semicolon are considered to be errors. This is not apparent until there are too many (somewhere around 100) such statements.
![too many errors](https://user-images.githubusercontent.com/362586/83957288-e7444c00-a834-11ea-8c58-95fdf3a0ddb9.png)

**Comment by benfry** [comment]
Sorry for the lack of response on this… if you (or anyone else who runs into this) can share example code that reproduces it, I can take a look. I'm guessing there's something odd happening with the feedback coming from the linter when it's overloaded. 

Also might be necessary to make it possible to tweak the linting options since no semicolons is also ok, it just depends on the style you're using. (I didn't make this the default because I find it trickier for beginners to learn to code without semicolons in JS—the way things fail is just so quirky.)

**Comment by benfry** [comment]
Turning off the warnings for no semicolons for the next release (version 1.5).
